package naitsirc98.beryl.audio;

public enum AudioDistanceModel {

    EXPONENT_DISTANCE,
    EXPONENT_DISTANCE_CLAMPED,
    INVERSE_DISTANCE,
    INVERSE_DISTANCE_CLAMPED,
    LINEAR_DISTANCE,
    LINEAR_DISTANCE_CLAMPED
}
